version: "3.5"
services:
  frontend:
    # Without this, the container exits immediately :/
    stdin_open: true
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - "./frontend:/client"
    networks:
      - internal_network
    expose:
      - "3000"
    ports:
      - "3000:3000"
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - "./backend:/server"
    networks:
      - internal_network
    expose:
      - "8000"
    ports:
      - "8000:8000"


networks:
  internal_network:
    name: custom_network
    driver: bridge



